### ISSUE TITLE
커뮤니티 TODO

### ISSUE THREAD

**Issue by yonghanJu** [Team-Walkie/Walkie#60]
## 커뮤니티 TODO
- [x] 상대방  프로필 화면 구현
- [x] 친구 클릭시 프로필 화면으로 이동
- [x] 친구 검색 후 클릭 시 프로필 화면으로 이동
- [x] uid 기반으로 user 데이터 가져오기 연결
- [x] onSettingsClicked 상대 화면일때 없에기(우상단)
- [x] 포스트 디자인 최신화
- [x] 커뮤니티 타이틀 옆 버튼 변경
- [x] 게시글에 댓글 수 표시
- [ ] 마이페이지 프로필 사진 서버에서 가져오도록 수정(데이터 지우면 사라질 수 있음)
